// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PendosManagementSystem.Data;

#nullable disable

namespace PendosManagementSystem.Migrations
{
    [DbContext(typeof(PendosManagementSystemContext))]
    [Migration("20250205062756_estimateborrowtime")]
    partial class estimateborrowtime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PM_Schema")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PendosManagementSystem.Models.IFXBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IFXBuilding", "PM_Schema");
                });

            modelBuilder.Entity("PendosManagementSystem.Models.Requestor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BadgeUser")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditionalPICStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditionalPICStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditionalPurposeTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditionalSCCStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditionalSCCStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditionalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimateBorrowEnd")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimateBorrowStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalReadingPendos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IFXBuilding")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICEMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PICStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SCCEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCCStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SCCStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("XrayRooms")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IFXBuilding");

                    b.HasIndex("XrayRooms");

                    b.ToTable("Requestors", "PM_Schema");
                });

            modelBuilder.Entity("PendosManagementSystem.Models.ValidUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BadgeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ValidUser", "PM_Schema");
                });

            modelBuilder.Entity("PendosManagementSystem.Models.XrayRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("XrayRooms", "PM_Schema");
                });

            modelBuilder.Entity("PendosManagementSystem.Models.Requestor", b =>
                {
                    b.HasOne("PendosManagementSystem.Models.IFXBuilding", null)
                        .WithMany()
                        .HasForeignKey("IFXBuilding")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PendosManagementSystem.Models.XrayRoom", null)
                        .WithMany()
                        .HasForeignKey("XrayRooms")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PendosManagementSystem.Models.XrayRoom", b =>
                {
                    b.HasOne("PendosManagementSystem.Models.IFXBuilding", "Building")
                        .WithMany("XrayRooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("PendosManagementSystem.Models.IFXBuilding", b =>
                {
                    b.Navigation("XrayRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
